coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_base: false
  require_changes: false
